spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: chenjunlang
    password: xxxxx
    virtual-host: /test
  mail:
    username: 18206176932@163.com
    password: xxxxx
    host: smtp.163.com
  security:
    jwt:
      key: 123456
      expire: 7
    filter:
      order: -100
  data:
    redis:
      host: 127.0.0.1
      database: 0
      connect-timeout: 10000
      port: 6379
  datasource:
    username: root
    password: xxxxx
    url: jdbc:mysql://localhost:3306/jwt
    driver-class-name: com.mysql.cj.jdbc.Driver
